export const dynamic = "force-dynamic";

import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { successResponse, errorResponse, requireAuth } from "@/lib/api-utils";

/**
 * GET /api/dashboard/stats
 *
 * Returns accurate dashboard statistics via Prisma `count()` / `aggregate()` — NOT
 * client-side counting from paginated article lists (which gives wrong numbers
 * when total exceeds fetch limit).
 *
 * For creators (JOURNALIST/CONTRIBUTOR), scopes to their authored articles.
 * For editors/admins, returns global stats.
 */
export async function GET(request: NextRequest) {
  try {
    const session = await requireAuth();
    const userRole = session.user.role;
    const userId = session.user.id;

    const isCreator = userRole === "JOURNALIST" || userRole === "CONTRIBUTOR";
    const authorFilter = isCreator ? { authorId: userId } : {};

    const now = new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

    // Run all counts in parallel for speed
    const [
      totalArticles,
      totalViewsAgg,
      pendingReviewCount,
      publishedCount,
      scheduledCount,
      todayPublishedCount,
      thisWeekPublishedCount,
      autoArticleCount,
      draftCount,
      rejectedCount,
      approvedTodayCount,
      sorotanTotal,
      reportsPending,
      viralArticles,
    ] = await Promise.all([
      // Total articles (all statuses)
      prisma.article.count({ where: authorFilter }),

      // Sum of viewCount across PUBLISHED articles (authoritative total views)
      prisma.article.aggregate({
        _sum: { viewCount: true },
        where: { ...authorFilter, status: "PUBLISHED" },
      }),

      // Pending review count
      prisma.article.count({ where: { ...authorFilter, status: "IN_REVIEW" } }),

      // Published count
      prisma.article.count({ where: { ...authorFilter, status: "PUBLISHED" } }),

      // Scheduled articles (APPROVED + scheduledAt set)
      prisma.article.count({
        where: { ...authorFilter, status: "APPROVED", scheduledAt: { not: null } },
      }),

      // Articles published today
      prisma.article.count({
        where: { ...authorFilter, status: "PUBLISHED", publishedAt: { gte: startOfToday } },
      }),

      // Articles published this week (for alert)
      prisma.article.count({
        where: { ...authorFilter, status: "PUBLISHED", publishedAt: { gte: weekAgo } },
      }),

      // Auto-generated articles (only admins/editors care about this)
      isCreator
        ? Promise.resolve(0)
        : prisma.article.count({ where: { isAutoGenerated: true } }),

      // Drafts count
      prisma.article.count({ where: { ...authorFilter, status: "DRAFT" } }),

      // Rejected (for editor dashboard)
      prisma.article.count({ where: { ...authorFilter, status: "REJECTED" } }),

      // Approved today (for editor dashboard)
      isCreator
        ? Promise.resolve(0)
        : prisma.article.count({
            where: {
              OR: [
                { status: "APPROVED", reviewedAt: { gte: startOfToday } },
                { status: "PUBLISHED", publishedAt: { gte: startOfToday } },
              ],
            },
          }),

      // Total Sorotan SEO (only admins/editors)
      isCreator ? Promise.resolve(0) : prisma.sorotan.count(),

      // Reports pending (only admins/editors)
      isCreator
        ? Promise.resolve(0)
        : prisma.report.count({ where: { status: "PENDING" } }),

      // Top 3 viral articles (>= 50 views) — for alerts
      prisma.article.findMany({
        where: {
          ...authorFilter,
          status: "PUBLISHED",
          viewCount: { gte: 50 },
        },
        select: { id: true, title: true, viewCount: true },
        orderBy: { viewCount: "desc" },
        take: 3,
      }),
    ]);

    return successResponse({
      totalArticles,
      totalViews: totalViewsAgg._sum.viewCount || 0,
      pendingReview: pendingReviewCount,
      published: publishedCount,
      scheduled: scheduledCount,
      todayPublished: todayPublishedCount,
      thisWeekPublished: thisWeekPublishedCount,
      autoArticleCount,
      draftCount,
      rejectedCount,
      approvedTodayCount,
      sorotanTotal,
      reportsPending,
      viralArticles,
    });
  } catch (error) {
    return errorResponse(error);
  }
}
