import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { ApiError, successResponse, errorResponse, requireRole } from "@/lib/api-utils";
import { slugify, calculateReadTime } from "@/lib/utils";
import { callAI, hasAIKey } from "@/lib/ai-client";

export const dynamic = "force-dynamic";

const FALLBACK_KEYWORDS = [
  "hukum bandung",
  "berita hukum bandung",
  "pengadilan bandung",
  "sidang bandung",
  "hukum pidana bandung",
  "hukum perdata bandung",
  "korupsi jawa barat",
  "kasus hukum bandung",
  "berita hukum jawa barat",
  "advokat bandung",
  "pengacara bandung",
  "hukum tata negara",
  "HAM bandung",
  "tipikor bandung",
  "kejaksaan bandung",
];


async function getTargetKeywords(): Promise<string[]> {
  try {
    const active = await prisma.targetKeyword.findMany({
      where: { isActive: true },
      select: { keyword: true },
    });
    const list = active.map((k) => k.keyword);
    return list.length > 0 ? list : FALLBACK_KEYWORDS;
  } catch {
    return FALLBACK_KEYWORDS;
  }
}

const AUTO_ARTICLE_SYSTEM = "Kamu adalah jurnalis senior media berita hukum 'Jurnalis Hukum Bandung'. Tulis artikel berita dalam Bahasa Indonesia yang profesional, informatif, dan berdasarkan fakta. Gunakan gaya penulisan jurnalistik berita (5W+1H). Jangan gunakan markdown formatting seperti ** atau ##, tulis dalam format HTML dengan tag <h2>, <h3>, <p>, <ul>, <li>, <blockquote>.";

async function callAIWithRetry(prompt: string, maxTokens = 2000, retries = 2): Promise<string> {
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const text = await callAI(AUTO_ARTICLE_SYSTEM, prompt, maxTokens, 90000);
      if (text) return text;
      if (attempt < retries) { await new Promise((r) => setTimeout(r, 3000)); continue; }
    } catch (e) {
      if (attempt < retries) {
        console.log(`[AUTO-ARTICLE] Attempt ${attempt + 1} failed, retrying...`);
        await new Promise((r) => setTimeout(r, 3000));
        continue;
      }
      throw e;
    }
  }
  throw new Error("AI failed after retries");
}

async function generateArticle(tagName?: string, tagId?: string) {
  // 1. Pick keyword — use tag name if provided, else random from DB-backed list
  const keywords = await getTargetKeywords();
  const keyword = tagName || keywords[Math.floor(Math.random() * keywords.length)];
  const relatedKeywords = keywords.filter((k) => k !== keyword).sort(() => Math.random() - 0.5).slice(0, 3);

  // 2. Pick 1 RANDOM published article (NOT auto-generated), filtered by tag if provided
  const sourceWhere = tagId
    ? { status: "PUBLISHED" as const, isAutoGenerated: false, tags: { some: { id: tagId } } }
    : { status: "PUBLISHED" as const, isAutoGenerated: false };

  const publishedCount = await prisma.article.count({ where: sourceWhere });
  if (publishedCount === 0) throw new Error("No published articles to paraphrase" + (tagId ? " for this tag" : ""));

  const randomSkip = Math.floor(Math.random() * publishedCount);
  const sourceArticle = await prisma.article.findFirst({
    where: sourceWhere,
    skip: randomSkip,
    select: {
      id: true,
      title: true,
      content: true,
      excerpt: true,
      featuredImage: true,
      categoryId: true,
      category: { select: { name: true } },
      tags: { select: { name: true } },
      sources: { select: { name: true, institution: true } },
      author: { select: { name: true } },
    },
  });
  if (!sourceArticle) throw new Error("No source article found");

  // 3. Extract full content + metadata from source article
  const fullContent = sourceArticle.content?.replace(/<[^>]*>/g, "").slice(0, 3000) || "";
  const sourcesStr = sourceArticle.sources?.map((s) => `${s.name}${s.institution ? ` (${s.institution})` : ""}`).join(", ") || "";
  const tagsStr = sourceArticle.tags?.map((t) => t.name).join(", ") || "";

  // 4. Collect all images from source article (featuredImage + inline content images)
  const allImageUrls: string[] = [];
  if (sourceArticle.featuredImage) allImageUrls.push(sourceArticle.featuredImage);
  const contentImgTags = sourceArticle.content?.match(/<img[^>]+>/gi) || [];
  for (const imgTag of contentImgTags) {
    const srcMatch = imgTag.match(/src=["']([^"']+)["']/i);
    if (srcMatch?.[1] && !allImageUrls.includes(srcMatch[1])) allImageUrls.push(srcMatch[1]);
  }
  // Use 2nd image as featuredImage if ≥2 exist, otherwise use 1st
  const chosenFeaturedImage = allImageUrls.length >= 2 ? allImageUrls[1] : allImageUrls[0] || null;

  // 6. Generate paraphrased article with DeepSeek
  const prompt = `Kamu adalah jurnalis senior "Jurnalis Hukum Bandung". Tugasmu adalah MENULIS ULANG (paraphrase) berita di bawah ini. Informasi dan fakta TETAP SAMA, tapi kata-kata dan struktur HARUS BERBEDA.

=== BERITA ASLI YANG HARUS DI-PARAPHRASE ===
Judul: ${sourceArticle.title}
Penulis: ${sourceArticle.author?.name || "Redaksi"}
Kategori: ${sourceArticle.category?.name || "-"}
Tags: ${tagsStr}
Narasumber: ${sourcesStr}
Isi lengkap:
${fullContent}
=== AKHIR BERITA ASLI ===

KEYWORD UTAMA: "${keyword}"
KEYWORD PENDUKUNG: ${relatedKeywords.map((k) => `"${k}"`).join(", ")}

INSTRUKSI PARAPHRASE + SEO:
1. TULIS ULANG seluruh berita dengan kata-kata BERBEDA, struktur kalimat BERBEDA, sudut pandang SEDIKIT BERBEDA
2. PERTAHANKAN semua fakta, nama orang, angka, kutipan narasumber — JANGAN ubah fakta
3. Ubah urutan paragraf, gunakan sinonim, variasi kalimat
4. WAJIB sisipkan keyword "${keyword}" di: judul, paragraf pertama, minimal 1 heading, 3-5x di isi
5. Sisipkan keyword pendukung masing-masing 1-2x secara natural
6. Sebut "Bandung" atau "Jawa Barat" minimal 2x
7. Tulis 400-600 kata dalam HTML (<p>, <h2>, <h3>, <blockquote>)
8. JANGAN gunakan markdown, HANYA HTML tags
9. Harus natural — BUKAN keyword stuffing

FORMAT OUTPUT (HARUS persis):
JUDUL: [judul baru mengandung "${keyword}"]
SEO_TITLE: [maks 60 char, mengandung "${keyword}"]
SEO_DESC: [maks 155 char, mengandung "${keyword}"]
EXCERPT: [ringkasan 1-2 kalimat, mengandung "${keyword}"]
TAGS: [${keyword}, tag2, tag3, tag4, tag5]
KONTEN:
[isi paraphrase dalam HTML]`;

  const result = await callAIWithRetry(prompt, 2500);

  // 7. Parse result — robust parsing with fallbacks
  const titleMatch = result.match(/JUDUL:\s*(.+)/i);
  const seoTitleMatch = result.match(/SEO_TITLE:\s*(.+)/i);
  const seoDescMatch = result.match(/SEO_DESC:\s*(.+)/i);
  const excerptMatch = result.match(/EXCERPT:\s*(.+)/i);
  const tagsMatch = result.match(/TAGS:\s*(.+)/i);
  const contentMatch = result.match(/KONTEN:\s*([\s\S]+)/i);

  // Fallback: if no JUDUL/KONTEN markers, treat entire response as content
  let title: string;
  let content: string;

  if (titleMatch && contentMatch) {
    title = titleMatch[1].trim().replace(/^["']|["']$/g, "");
    content = contentMatch[1].trim();
  } else {
    // AI didn't follow format — extract title from first <h2> or first line
    const h2Match = result.match(/<h2[^>]*>(.*?)<\/h2>/i);
    const firstLine = result.split("\n").find((l) => l.trim().length > 10);
    title = h2Match ? h2Match[1].replace(/<[^>]*>/g, "").trim() : firstLine?.replace(/<[^>]*>/g, "").trim().slice(0, 100) || `${keyword} — ${sourceArticle.category?.name || "Berita"} Terbaru`;
    content = result;
    console.log("[AUTO-ARTICLE] AI response didn't follow format, using fallback parsing");
  }

  const seoTitle = seoTitleMatch?.[1]?.trim().slice(0, 60) || title.slice(0, 60);
  const seoDescription = seoDescMatch?.[1]?.trim().slice(0, 155) || title;
  const excerpt = excerptMatch?.[1]?.trim() || content.replace(/<[^>]*>/g, "").slice(0, 200);
  const parsedTags = tagsMatch?.[1]?.split(",").map((t: string) => t.trim()).filter(Boolean) || [];
  const tags = Array.from(new Set([keyword, ...relatedKeywords.slice(0, 2), ...parsedTags])).slice(0, 8);

  // 8. Insert chosen image at start of content
  if (chosenFeaturedImage) {
    const imgTag = `<img src="${chosenFeaturedImage}" alt="${title}" title="Dok. JHB" style="width: 100%">`;
    content = imgTag + content;
  }
  // Also insert any additional inline images from source article after paragraph 3
  if (contentImgTags.length > 1) {
    const paragraphs = content.split("</p>");
    if (paragraphs.length > 3) {
      paragraphs.splice(3, 0, contentImgTags[1]);
      content = paragraphs.join("</p>");
    }
  }

  // 9. Generate unique slug — check for conflicts
  const baseSlug = slugify(title).slice(0, 70);
  let slug = `${baseSlug}-${Date.now().toString(36)}`;
  const existingSlug = await prisma.article.findUnique({ where: { slug } });
  if (existingSlug) slug = `${baseSlug}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;

  // 10. Get "Redaksi" user as author
  let author = await prisma.user.findFirst({
    where: { name: { contains: "Redaksi", mode: "insensitive" }, isActive: true },
    select: { id: true },
  });
  if (!author) {
    author = await prisma.user.findFirst({
      where: { role: "SUPER_ADMIN", isActive: true },
      select: { id: true },
    });
  }
  if (!author) throw new Error("No author user found");

  // 11. Ensure tags exist
  const tagConnections = [];
  for (const tagName of tags) {
    const tagSlug = slugify(tagName);
    if (!tagName || !tagSlug) continue;
    try {
      let tag = await prisma.tag.findFirst({ where: { OR: [{ name: tagName }, { slug: tagSlug }] } });
      if (!tag) tag = await prisma.tag.create({ data: { name: tagName, slug: tagSlug } });
      tagConnections.push({ id: tag.id });
    } catch { /* skip */ }
  }

  // 12. Save as DRAFT — marked as auto-generated, linked to source article
  const article = await prisma.article.create({
    data: {
      title,
      slug,
      content,
      excerpt,
      featuredImage: chosenFeaturedImage || null,
      seoTitle: seoTitle || undefined,
      seoDescription: seoDescription || undefined,
      status: "DRAFT",
      readTime: calculateReadTime(content),
      authorId: author.id,
      categoryId: sourceArticle.categoryId, // Same category as source
      coAuthors: "Tim Redaksi",
      verificationLabel: "UNVERIFIED",
      isAutoGenerated: true,
      sourceArticleId: sourceArticle.id,
      tags: { connect: tagConnections },
    },
    select: { id: true, title: true, slug: true },
  });

  return { article, keyword, sourceTitle: sourceArticle.title, imageUsed: !!chosenFeaturedImage };
}

async function handleAutoArticle(request: NextRequest) {
  try {
    // Auth: cron secret OR admin session (logged in)
    const authHeader = request.headers.get("authorization");
    const isCron = authHeader === `Bearer ${process.env.CRON_SECRET}`;
    if (!isCron) {
      // Try session auth — only SUPER_ADMIN/EDITOR
      await requireRole(["SUPER_ADMIN", "EDITOR"]);
    }

    // Check if auto-article is enabled
    const enabledSetting = await prisma.systemSetting.findUnique({
      where: { key: "auto_article_enabled" },
    });
    if (enabledSetting?.value === "false") {
      return successResponse({ message: "Auto-article is disabled", generated: 0 });
    }

    // Get count + optional tag filter from request body
    let requestCount = 0;
    let tagId: string | undefined;
    let tagName: string | undefined;
    try {
      const body = await request.json().catch(() => ({}));
      if (body.count) requestCount = parseInt(body.count);
      if (body.tagId) tagId = body.tagId;
      if (body.tagName) tagName = body.tagName;
    } catch { /* ignore */ }

    const countSetting = await prisma.systemSetting.findUnique({
      where: { key: "auto_article_count" },
    });
    const count = Math.min(10, Math.max(1, requestCount || parseInt(countSetting?.value || "1")));

    if (!(await hasAIKey())) {
      return successResponse({ message: "AI API key not configured", generated: 0 });
    }

    const results = [];
    for (let i = 0; i < count; i++) {
      try {
        const result = await generateArticle(tagName, tagId);
        results.push({ success: true, ...result });
      } catch (e) {
        results.push({ success: false, error: String(e).slice(0, 100) });
      }
      // Delay between generations
      if (i < count - 1) await new Promise((r) => setTimeout(r, 2000));
    }

    return successResponse({
      generated: results.filter((r) => r.success).length,
      failed: results.filter((r) => !r.success).length,
      results,
    });
  } catch (error) {
    return errorResponse(error);
  }
}

export async function GET(request: NextRequest) {
  return handleAutoArticle(request);
}

export async function POST(request: NextRequest) {
  return handleAutoArticle(request);
}
