import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { ApiError, successResponse, errorResponse, requireRole } from "@/lib/api-utils";
import { slugify, calculateReadTime } from "@/lib/utils";

export const dynamic = "force-dynamic";

const TARGET_KEYWORDS = [
  "hukum bandung",
  "berita hukum bandung",
  "pengadilan bandung",
  "sidang bandung",
  "hukum pidana bandung",
  "hukum perdata bandung",
  "korupsi jawa barat",
  "kasus hukum bandung",
  "berita hukum jawa barat",
  "advokat bandung",
  "pengacara bandung",
  "hukum tata negara",
  "HAM bandung",
  "tipikor bandung",
  "kejaksaan bandung",
];

async function getDeepSeekKey(): Promise<string | null> {
  const setting = await prisma.systemSetting.findUnique({
    where: { key: "deepseek_api_key" },
  });
  return setting?.value || null;
}

async function callDeepSeek(apiKey: string, prompt: string, maxTokens = 2000): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 60000);
  try {
    const res = await fetch("https://api.deepseek.com/v1/chat/completions", {
      method: "POST",
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "deepseek-chat",
        messages: [
          {
            role: "system",
            content:
              "Kamu adalah jurnalis senior media berita hukum 'Jurnalis Hukum Bandung'. Tulis artikel berita dalam Bahasa Indonesia yang profesional, informatif, dan berdasarkan fakta. Gunakan gaya penulisan jurnalistik berita (5W+1H). Jangan gunakan markdown formatting seperti ** atau ##, tulis dalam format HTML dengan tag <h2>, <h3>, <p>, <ul>, <li>, <blockquote>.",
          },
          { role: "user", content: prompt },
        ],
        max_tokens: maxTokens,
        temperature: 0.8,
      }),
    });
    if (!res.ok) throw new Error(`DeepSeek API error: ${res.status}`);
    const data = await res.json();
    return data.choices?.[0]?.message?.content?.trim() || "";
  } finally {
    clearTimeout(timeout);
  }
}

async function generateArticle(apiKey: string) {
  // 1. Pick random keyword for SEO
  const keyword = TARGET_KEYWORDS[Math.floor(Math.random() * TARGET_KEYWORDS.length)];
  const relatedKeywords = TARGET_KEYWORDS.filter((k) => k !== keyword).sort(() => Math.random() - 0.5).slice(0, 3);

  // 2. Pick 1 RANDOM existing published article (NOT auto-generated) to paraphrase
  const publishedCount = await prisma.article.count({
    where: { status: "PUBLISHED", isAutoGenerated: false },
  });
  if (publishedCount === 0) throw new Error("No published articles to paraphrase");

  const randomSkip = Math.floor(Math.random() * publishedCount);
  const sourceArticle = await prisma.article.findFirst({
    where: { status: "PUBLISHED", isAutoGenerated: false },
    skip: randomSkip,
    select: {
      id: true,
      title: true,
      content: true,
      excerpt: true,
      featuredImage: true,
      categoryId: true,
      category: { select: { name: true } },
      tags: { select: { name: true } },
      sources: { select: { name: true, institution: true } },
      author: { select: { name: true } },
    },
  });
  if (!sourceArticle) throw new Error("No source article found");

  // 3. Extract full content + metadata from source article
  const fullContent = sourceArticle.content?.replace(/<[^>]*>/g, "").slice(0, 3000) || "";
  const sourcesStr = sourceArticle.sources?.map((s) => `${s.name}${s.institution ? ` (${s.institution})` : ""}`).join(", ") || "";
  const tagsStr = sourceArticle.tags?.map((t) => t.name).join(", ") || "";

  // 4. Use SAME image as source article
  const imageUrl = sourceArticle.featuredImage;

  // 5. Extract all images from source article content
  const contentImages = sourceArticle.content?.match(/<img[^>]+>/g) || [];

  // 6. Generate paraphrased article with DeepSeek
  const prompt = `Kamu adalah jurnalis senior "Jurnalis Hukum Bandung". Tugasmu adalah MENULIS ULANG (paraphrase) berita di bawah ini. Informasi dan fakta TETAP SAMA, tapi kata-kata dan struktur HARUS BERBEDA.

=== BERITA ASLI YANG HARUS DI-PARAPHRASE ===
Judul: ${sourceArticle.title}
Penulis: ${sourceArticle.author?.name || "Redaksi"}
Kategori: ${sourceArticle.category?.name || "-"}
Tags: ${tagsStr}
Narasumber: ${sourcesStr}
Isi lengkap:
${fullContent}
=== AKHIR BERITA ASLI ===

KEYWORD UTAMA: "${keyword}"
KEYWORD PENDUKUNG: ${relatedKeywords.map((k) => `"${k}"`).join(", ")}

INSTRUKSI PARAPHRASE + SEO:
1. TULIS ULANG seluruh berita dengan kata-kata BERBEDA, struktur kalimat BERBEDA, sudut pandang SEDIKIT BERBEDA
2. PERTAHANKAN semua fakta, nama orang, angka, kutipan narasumber — JANGAN ubah fakta
3. Ubah urutan paragraf, gunakan sinonim, variasi kalimat
4. WAJIB sisipkan keyword "${keyword}" di: judul, paragraf pertama, minimal 1 heading, 3-5x di isi
5. Sisipkan keyword pendukung masing-masing 1-2x secara natural
6. Sebut "Bandung" atau "Jawa Barat" minimal 2x
7. Tulis 400-600 kata dalam HTML (<p>, <h2>, <h3>, <blockquote>)
8. JANGAN gunakan markdown, HANYA HTML tags
9. Harus natural — BUKAN keyword stuffing

FORMAT OUTPUT (HARUS persis):
JUDUL: [judul baru mengandung "${keyword}"]
SEO_TITLE: [maks 60 char, mengandung "${keyword}"]
SEO_DESC: [maks 155 char, mengandung "${keyword}"]
EXCERPT: [ringkasan 1-2 kalimat, mengandung "${keyword}"]
TAGS: [${keyword}, tag2, tag3, tag4, tag5]
KONTEN:
[isi paraphrase dalam HTML]`;

  const result = await callDeepSeek(apiKey, prompt, 2500);

  // 7. Parse result
  const titleMatch = result.match(/JUDUL:\s*(.+)/);
  const seoTitleMatch = result.match(/SEO_TITLE:\s*(.+)/);
  const seoDescMatch = result.match(/SEO_DESC:\s*(.+)/);
  const excerptMatch = result.match(/EXCERPT:\s*(.+)/);
  const tagsMatch = result.match(/TAGS:\s*(.+)/);
  const contentMatch = result.match(/KONTEN:\s*([\s\S]+)/);

  if (!titleMatch || !contentMatch) throw new Error("Failed to parse AI response");

  const title = titleMatch[1].trim();
  const seoTitle = seoTitleMatch?.[1]?.trim().slice(0, 60) || "";
  const seoDescription = seoDescMatch?.[1]?.trim().slice(0, 155) || "";
  let content = contentMatch[1].trim();
  const excerpt = excerptMatch?.[1]?.trim() || "";
  const parsedTags = tagsMatch?.[1]?.split(",").map((t: string) => t.trim()).filter(Boolean) || [];
  const tags = Array.from(new Set([keyword, ...relatedKeywords.slice(0, 2), ...parsedTags])).slice(0, 8);

  // 8. Insert SAME images from source article into paraphrased content
  if (imageUrl) {
    const imgTag = `<img src="${imageUrl}" alt="${title}" title="Dok. JHB" style="width: 100%">`;
    content = imgTag + content;
  }
  // Also insert any inline images from source article
  if (contentImages.length > 1) {
    const paragraphs = content.split("</p>");
    if (paragraphs.length > 3) {
      // Insert 2nd image after 3rd paragraph
      paragraphs.splice(3, 0, contentImages[1]);
      content = paragraphs.join("</p>");
    }
  }

  // 9. Generate unique slug
  const baseSlug = slugify(title).slice(0, 80);
  const slug = `${baseSlug}-${Date.now().toString(36)}`;

  // 10. Get "Redaksi" user as author
  let author = await prisma.user.findFirst({
    where: { name: { contains: "Redaksi", mode: "insensitive" }, isActive: true },
    select: { id: true },
  });
  if (!author) {
    author = await prisma.user.findFirst({
      where: { role: "SUPER_ADMIN", isActive: true },
      select: { id: true },
    });
  }
  if (!author) throw new Error("No author user found");

  // 11. Ensure tags exist
  const tagConnections = [];
  for (const tagName of tags) {
    const tagSlug = slugify(tagName);
    if (!tagName || !tagSlug) continue;
    try {
      let tag = await prisma.tag.findFirst({ where: { OR: [{ name: tagName }, { slug: tagSlug }] } });
      if (!tag) tag = await prisma.tag.create({ data: { name: tagName, slug: tagSlug } });
      tagConnections.push({ id: tag.id });
    } catch { /* skip */ }
  }

  // 12. Save as DRAFT — marked as auto-generated, linked to source article
  const article = await prisma.article.create({
    data: {
      title,
      slug,
      content,
      excerpt,
      featuredImage: imageUrl || null,
      seoTitle: seoTitle || undefined,
      seoDescription: seoDescription || undefined,
      status: "DRAFT",
      readTime: calculateReadTime(content),
      authorId: author.id,
      categoryId: sourceArticle.categoryId, // Same category as source
      coAuthors: "Tim Redaksi",
      verificationLabel: "UNVERIFIED",
      isAutoGenerated: true,
      sourceArticleId: sourceArticle.id,
      tags: { connect: tagConnections },
    },
    select: { id: true, title: true, slug: true },
  });

  return { article, keyword, sourceTitle: sourceArticle.title, imageUsed: !!imageUrl };
}

async function handleAutoArticle(request: NextRequest) {
  try {
    // Auth: cron secret OR admin session (logged in)
    const authHeader = request.headers.get("authorization");
    const isCron = authHeader === `Bearer ${process.env.CRON_SECRET}`;
    if (!isCron) {
      // Try session auth — only SUPER_ADMIN/EDITOR
      await requireRole(["SUPER_ADMIN", "EDITOR"]);
    }

    // Check if auto-article is enabled
    const enabledSetting = await prisma.systemSetting.findUnique({
      where: { key: "auto_article_enabled" },
    });
    if (enabledSetting?.value === "false") {
      return successResponse({ message: "Auto-article is disabled", generated: 0 });
    }

    // Get count from request body or setting
    let requestCount = 0;
    try {
      const body = await request.json().catch(() => ({}));
      if (body.count) requestCount = parseInt(body.count);
    } catch { /* ignore */ }

    const countSetting = await prisma.systemSetting.findUnique({
      where: { key: "auto_article_count" },
    });
    const count = Math.min(10, Math.max(1, requestCount || parseInt(countSetting?.value || "1")));

    const apiKey = await getDeepSeekKey();
    if (!apiKey) {
      return successResponse({ message: "DeepSeek API key not configured", generated: 0 });
    }

    const results = [];
    for (let i = 0; i < count; i++) {
      try {
        const result = await generateArticle(apiKey);
        results.push({ success: true, ...result });
      } catch (e) {
        results.push({ success: false, error: String(e).slice(0, 100) });
      }
      // Delay between generations
      if (i < count - 1) await new Promise((r) => setTimeout(r, 2000));
    }

    return successResponse({
      generated: results.filter((r) => r.success).length,
      failed: results.filter((r) => !r.success).length,
      results,
    });
  } catch (error) {
    return errorResponse(error);
  }
}

export async function GET(request: NextRequest) {
  return handleAutoArticle(request);
}

export async function POST(request: NextRequest) {
  return handleAutoArticle(request);
}
