import Link from "next/link";
import { Search, Home, ArrowRight, Newspaper, Flame } from "lucide-react";
import { prisma } from "@/lib/prisma";
import ArticleCard from "@/components/artikel/ArticleCard";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function NotFound() {
  const articleSelect = {
    id: true,
    title: true,
    slug: true,
    excerpt: true,
    featuredImage: true,
    publishedAt: true,
    viewCount: true,
    readTime: true,
    verificationLabel: true,
    author: { select: { name: true } },
    category: { select: { name: true, slug: true } },
  } as const;

  const [latestArticles, trendingArticles, categories] = await Promise.all([
    prisma.article.findMany({
      where: { status: "PUBLISHED", isAutoGenerated: false },
      select: articleSelect,
      orderBy: { publishedAt: "desc" },
      take: 6,
    }),
    prisma.article.findMany({
      where: { status: "PUBLISHED", isAutoGenerated: false },
      select: articleSelect,
      orderBy: { viewCount: "desc" },
      take: 5,
    }),
    prisma.category.findMany({
      where: { articles: { some: { status: "PUBLISHED" } } },
      select: { name: true, slug: true },
      orderBy: { order: "asc" },
      take: 8,
    }),
  ]);

  return (
    <div className="bg-surface min-h-[70vh]">
      <div className="container-main py-12 sm:py-16">
        {/* Header 404 */}
        <div className="text-center max-w-2xl mx-auto">
          <div className="mb-4">
            <span className="text-7xl font-extrabold text-goto-green/20 sm:text-8xl select-none">
              404
            </span>
          </div>

          <h1 className="text-2xl font-bold text-txt-primary sm:text-3xl">
            Halaman Tidak Ditemukan
          </h1>
          <p className="mt-3 text-txt-secondary">
            Maaf, halaman yang Anda cari tidak tersedia atau telah dipindahkan.
            Silakan kembali ke beranda atau baca artikel terbaru di bawah ini.
          </p>

          {/* Search bar */}
          <form action="/search" method="GET" className="mt-6 mx-auto max-w-lg">
            <div className="relative">
              <Search
                size={18}
                className="absolute left-4 top-1/2 -translate-y-1/2 text-txt-muted"
              />
              <input
                type="text"
                name="q"
                placeholder="Cari berita hukum..."
                className="input w-full py-3 pl-12 pr-4 text-base"
              />
            </div>
          </form>

          {/* Action buttons */}
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <Link href="/" className="btn-primary">
              <Home size={16} />
              Kembali ke Beranda
            </Link>
            <Link href="/berita" className="btn-secondary">
              <Newspaper size={16} />
              Semua Berita
              <ArrowRight size={16} />
            </Link>
          </div>

          {/* Category quick links */}
          {categories.length > 0 && (
            <div className="mt-6 flex flex-wrap items-center justify-center gap-2">
              <span className="text-xs text-txt-muted">Jelajahi kategori:</span>
              {categories.map((cat) => (
                <Link
                  key={cat.slug}
                  href={`/kategori/${cat.slug}`}
                  className="text-xs font-semibold text-goto-green hover:underline"
                >
                  {cat.name}
                </Link>
              ))}
            </div>
          )}
        </div>

        {/* Artikel Terkini */}
        {latestArticles.length > 0 && (
          <section className="mt-14">
            <div className="section-header">
              <h2 className="section-title flex items-center gap-2">
                <Newspaper size={20} className="text-goto-green" />
                Baca Artikel Terkini
              </h2>
              <Link href="/berita" className="section-link">
                Lihat Semua
                <ArrowRight size={14} />
              </Link>
            </div>

            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {latestArticles.map((article) => (
                <ArticleCard
                  key={article.id}
                  title={article.title}
                  slug={article.slug}
                  excerpt={article.excerpt}
                  featuredImage={article.featuredImage}
                  category={article.category}
                  author={article.author}
                  publishedAt={article.publishedAt}
                  readTime={article.readTime}
                  viewCount={article.viewCount}
                  verificationLabel={article.verificationLabel || "UNVERIFIED"}
                  variant="standard"
                />
              ))}
            </div>
          </section>
        )}

        {/* Artikel Populer */}
        {trendingArticles.length > 0 && (
          <section className="mt-12">
            <div className="section-header">
              <h2 className="section-title flex items-center gap-2">
                <Flame size={20} className="text-goto-green" />
                Paling Banyak Dibaca
              </h2>
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {trendingArticles.map((article) => (
                <ArticleCard
                  key={article.id}
                  title={article.title}
                  slug={article.slug}
                  featuredImage={article.featuredImage}
                  category={article.category}
                  author={article.author}
                  publishedAt={article.publishedAt}
                  variant="compact"
                />
              ))}
            </div>
          </section>
        )}
      </div>
    </div>
  );
}
