// Shared types + utilities for dashboard sub-components

export interface Article {
  id: string;
  title: string;
  slug: string;
  status: string;
  viewCount: number;
  publishedAt: string | null;
  scheduledAt?: string | null;
  createdAt: string;
  updatedAt: string;
  reviewedAt?: string | null;
  author?: { name: string };
  category?: { name: string; id: string };
  reviewerName?: string | null;
  isAutoGenerated?: boolean;
}

export interface StatsItem {
  label: string;
  value: string;
  icon: React.ElementType;
  color: string;
  cardBg: string;
  borderColor: string;
}

export function formatNumber(num: number): string {
  return num.toLocaleString("id-ID");
}

export function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("id-ID", { day: "numeric", month: "short", year: "numeric" });
}

export function getTimeAgo(dateStr: string): string {
  const now = new Date().getTime();
  const then = new Date(dateStr).getTime();
  const diffMin = Math.floor((now - then) / 60000);
  if (diffMin < 1) return "Baru saja";
  if (diffMin < 60) return `${diffMin} menit lalu`;
  const diffHour = Math.floor(diffMin / 60);
  if (diffHour < 24) return `${diffHour} jam lalu`;
  const diffDay = Math.floor(diffHour / 24);
  if (diffDay < 30) return `${diffDay} hari lalu`;
  return new Date(dateStr).toLocaleDateString("id-ID", { day: "numeric", month: "short" });
}
