/**
 * Bulk delete articles by status + isAutoGenerated filter.
 *
 * POST /api/articles/bulk-delete
 *   Body: { status: "DRAFT"|"PUBLISHED"|"ARCHIVED"|"all", autoGeneratedOnly?: boolean }
 *
 * SUPER_ADMIN only. Used by /panel/auto-artikel "Hapus Semua" button.
 * Soft-fails if any article has FK constraints (e.g. references in social posts).
 */

export const dynamic = "force-dynamic";

import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireRole, successResponse, errorResponse } from "@/lib/api-utils";

const bodySchema = z.object({
  status: z.enum(["DRAFT", "PUBLISHED", "ARCHIVED", "all"]),
  autoGeneratedOnly: z.boolean().optional().default(true),
});

export async function POST(req: NextRequest) {
  try {
    await requireRole(["SUPER_ADMIN"]);
    const body = await req.json();
    const { status, autoGeneratedOnly } = bodySchema.parse(body);

    const where: { status?: "DRAFT" | "PUBLISHED" | "ARCHIVED"; isAutoGenerated?: boolean } = {};
    if (status !== "all") where.status = status;
    if (autoGeneratedOnly) where.isAutoGenerated = true;

    // Pre-count to return for confirmation message
    const totalToDelete = await prisma.article.count({ where });
    if (totalToDelete === 0) {
      return successResponse({ deleted: 0, message: "Tidak ada artikel yang cocok dengan filter" });
    }

    // Get IDs first so we can clean up related records (sorotan, social posts, tiktok videos)
    const articles = await prisma.article.findMany({
      where,
      select: { id: true },
    });
    const articleIds = articles.map((a) => a.id);

    // Cleanup related records that block delete (sorotan + tiktok videos + social posts have onDelete: SetNull)
    // Tags + revisions + comments + reports + corrections cascade via Prisma schema.
    // Just attempt deleteMany — Prisma will throw if there's a hard FK problem.
    const result = await prisma.article.deleteMany({
      where: { id: { in: articleIds } },
    });

    return successResponse({
      deleted: result.count,
      requested: totalToDelete,
      message: `${result.count} artikel dihapus`,
    });
  } catch (error) {
    return errorResponse(error);
  }
}
